version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: monitor
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d 
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend/so1_202001954/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
  db-data: {}

