CREATE DATABASE IF NOT EXISTS monitor;
USE monitor;

CREATE TABLE IF NOT EXISTS registro_uso_recursos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uso_cpu DECIMAL(5,2),
    uso_ram DECIMAL(5,2),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
